version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: techworks-postgres
    restart: always
    environment:
      POSTGRES_USER: techworks_user
      POSTGRES_PASSWORD: techworks_password
      POSTGRES_DB: techworks_quiz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techworks_user -d techworks_quiz"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    container_name: techworks-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: 